# NumPy와 SciPy

In [1]:
import numpy as np

##1 배열과 행렬 만들기


리스트를 먼저 만들고 array 함수를 사용해 배열을 만든다.

In [2]:
vec = [ 1, 2, 3, 4 ] # 네 개의 원소를 가진 리스트 vec를 만든다
vecA = np.array( vec ) # 리스트를 배열로 바꾼다
print( vecA )

[1 2 3 4]


array 함수로 행렬도 만들 수 있다. [ [ ],[ ] ] 형태로 다소 복잡해 보이지만, 안쪽의 []가 행을 의미한다. [1,2,3]과 [4,5,6]은 행이다. 그리고 열은 콤마로 구분된다.

In [3]:
vecB = np.array( [ [1, 2, 3], [4, 5, 6] ] ) # array( ) 함수에 직접 리스트를 입력한다
print( vecB )

[[1 2 3]
 [4 5 6]]


zeros 함수는 행렬의 구성 요소가 모두 0인 행렬을 만들어준다. 따라서 행렬의 차원만 지정하면 된다.



In [4]:
zeros = np.zeros( ( 2, 2 ) ) # 원소가 모두 0인 2x2 행렬을 만든다
print( zeros )

[[0. 0.]
 [0. 0.]]


ones 함수는 행렬의 구성 요소가 모두 1인 단위행렬을 만든다. zeros와 마찬가지로 행렬의 차원만 지정하면 된다.



In [5]:
ones = np.ones( ( 2, 3 ) ) # 원소가 모두 1인 2x3 행렬을 만든다
print( ones )

[[1. 1. 1.]
 [1. 1. 1.]]


full 함수는 지정한 행렬의 차원으로 지정한 값을 채운다.

In [6]:
fives = np.full( (2, 3), 5 ) # 원소가 모두 5인 2x3 행렬을 만든다
print( fives )

[[5 5 5]
 [5 5 5]]


eye 함수는 지정한 크기의 항등행렬(대각행렬)을 만든다.



In [7]:
eye = np.eye( 3 ) # 대각선상의 원소가 모두 1인 3x3 행렬을 만든다
print( eye )

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


앞서 array 함수로 배열을 만들었는데, 이 배열의 차원을 reshape 함수로 바꾸면 행렬을 만들 수 있다.

In [8]:
reshape = np.array( range(20) ).reshape( (4, 5) ) # 20개의 리스트를 만들어 4x5의 2차원 행렬을 만든다
print( reshape )


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


##2 배열과 행렬의 속성


In [9]:
print( vecA.dtype ) # 데이터 타입. int64는 저장된 데이터의 타입이다
print( vecA.shape ) # 행과 열의 개수. (4,)는 네 개의 원소를 가진 배열임을 의미한다
print( vecA.ndim ) # 차원. 1을 돌려준다. 즉, 1차원 배열임을 알 수 있다

int64
(4,)
1


In [10]:
print( vecB.dtype ) # 데이터 타입. int64는 저장된 데이터의 타입이다
print( vecB.shape ) # 행과 열의 개수. (2, 3)은 2행 3열이라는 의미다
print( vecB.ndim ) # 차원을 돌려준다. 2는 2차원 배열임을 의미한다
 

int64
(2, 3)
2


##3 연산


In [11]:
print( vecA*2+1 )    # 2를 곱한 후 1을 더하는 연산
print( vecA+vecA )   # 두 array 객체 더하기
print( vecA-vecA )   # 두 array 객체 빼기
print( 1/vecA )
print( vecA**2 )
print( vecA%2 )
print( np.dot( vecA.T, vecA ) ) # 벡터와 행렬의 내적 계산은 dot 함수를 사용한다

[3 5 7 9]
[2 4 6 8]
[0 0 0 0]
[1.         0.5        0.33333333 0.25      ]
[ 1  4  9 16]
[1 0 1 0]
30


##4 인덱싱/슬라이싱


In [12]:
print( vecA[0], vecA[1], vecA[2], vecA[3] )   # 배열의 각 인덱스 값을 출력한다
print( vecB[0,0], vecB[0,1], vecB[0,2] )      # 2차원 배열이라면 행과 열 인덱스로 출력한다
print( vecB[1,0], vecB[1,1], vecB[1,2] )

1 2 3 4
1 2 3
4 5 6


In [13]:
import numpy as np

vec = np.array( [ 19, 29, 39, 49 ] )
vec[ -4 ]

19

In [14]:
vec[ -3 ]

29

In [15]:
vec[-2]

39

In [16]:
vec[-1]

49

인덱스를 벗어난 값을 지정하면 에러가 발생한다.



In [17]:
# vec[ -5 ]

다음은 동일한 데이터를 가리키는 순방향과 역방향 인덱스를 사용한 예다.

In [18]:
print( vecA[0], vecA[-4] )
print( vecA[1], vecA[-3] )
print( vecA[2], vecA[-2] )
print( vecA[3], vecA[-1] )

1 1
2 2
3 3
4 4


In [19]:
print( vecA[1:3] ) # 인덱스 1부터 인덱스 3 직전, 즉 인덱스 1과 2가 가리키는 값을 가져온다

[2 3]


##5 난수 만들기

`random.seed`: 난수에 필요한 시드 값을 설정한다.

In [20]:
np.random.seed( 0 )
print( np.random.rand( 2, 3 ) )

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


`random.rand`: 난수 배열을 생성한다.

In [21]:
print( np.random.rand( 5 ) )
print( np.random.rand( 2, 3 ) )

[0.43758721 0.891773   0.96366276 0.38344152 0.79172504]
[[0.52889492 0.56804456 0.92559664]
 [0.07103606 0.0871293  0.0202184 ]]


`random.choice`: 1차원 배열에 임의의 샘플을 생성한다.

In [26]:
#np.arange(5)에서 샘플 세 개를 추출한 1차원 배열
print( np.random.choice( 5, 3 ) )
#np.arange(10)에서 샘플을 추출해 (2, 3)의 2차원 배열 생성
print( np.random.choice( 10, ( 2, 3 ) ))

[3 4 4]
[[4 3 4]
 [4 8 4]]


`random.randint`: 시작 값 ≤ 임의의 난수 < 끝 값, 즉 시작 값을 포함하고 끝 값을 포함하지 않는 정수 난수를 생성한다.

In [23]:
print( np.random.randint( 2, size=5 ) ) # 0≤난수<2
print( np.random.randint( 2, 4, size=5 ) ) # 2≤난수<4
print( np.random.randint( 1, 5, size=( 2, 3 ) ) ) # 1≤난수<5

[1 0 1 1 1]
[3 3 2 3 2]
[[2 2 2]
 [4 1 4]]


`random.randn`: 표준정규분포(standard normal distribution)를 따르는 난수를 생성한다.

In [24]:
# randn 함수는 임의의 표준정규분포 데이터를 만든다
rnd_num = np.random.randn( 4, 4 )
print( rnd_num )
print( rnd_num>0 ) # 생성한 난수 중 0 이상인 값만 출력
print( (rnd_num>0 ).sum( ) ) # 0 이상인 난수 값의 합계를 출력
print( rnd_num.mean( ), rnd_num.std( ), rnd_num.var( ) ) # 난수의 평균, 표준편차, 분산 출력

[[-0.06491034 -0.96898025  0.59124281 -0.7827755 ]
 [-0.44423283 -0.34518616 -0.88180055 -0.44265324]
 [-0.5409163  -1.32322737 -0.11279892  0.90734594]
 [ 0.81526991  0.22909795 -1.02617878  0.47752547]]
[[False False  True False]
 [False False False False]
 [False False False  True]
 [ True  True False  True]]
5
-0.24457363539097582 0.6669022381617189 0.44475859526510997
