# Numpy 사용해보기
Numpy 라이브러리는 리스트를 입력으로 받아서 Numpy 객체를 만들 수 있도록 해줍니다.



In [1]:
import numpy as np

array = np.array([1, 2, 3])

print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소



3
int64
3


# Numpy로 배열 만들기
Numpy에서 배열을 순식간에 생성하기 위해서는 arange() 함수를 사용할 수 있습니다. arange() 함수를 이용하면 0부터 특정 인덱스까지의 배열을 생성할 수 있습니다.


In [2]:
import numpy as np

array1 = np.arange(4)
print(array1[3])



3


# Numpy 배열 합치기
  concatenate() 함수를 이용하면 여러 배열을 하나로 합칠 수 있습니다.

In [3]:
import numpy as np
array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6]) 
array3 = np.concatenate([array1, array2])
print(array3.shape)



(6,)


# Numpy 다양한 형태의 배열 만들기

In [4]:
import numpy as np

array1 = np.zeros((4, 4), dtype=float)
array2 = np.ones((3, 3), dtype=str)
array3 = np.random.randint(0, 10, (3, 3))
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 값
array4 = np.random.normal(0, 1, (3, 3))
print(array1)
print(array2)
print(array3)
print(array4)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[4 1 1]
 [1 5 2]
 [0 7 6]]
[[-0.69859363  1.39280631  0.67766382]
 [-0.1330376  -2.26421517 -0.3235079 ]
 [-1.73369645 -0.84539246  1.01663142]]


# Numpy 배열의 형태 바꾸기
reshape() 함수를 이용하면, 기존 배열의 형태를 바꿀 수 있습니다. 예를 들어서 1차원 배열을 2차원 배열로 바꿀 수 있습니다.


In [5]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))

print(array2.shape)



(2, 2)


# Numpy 배열을 세로 축으로 합치기
Numpy 배열은 세로 축으로 합칠 수도 있습니다. 기본적으로 축 값(Axis)이 0이라면 세로 축이고, 1이라면 가로 축입니다.

In [6]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

array3 = np.concatenate([array1, array2], axis=0)
print(array3.shape)



(3, 4)


# Numpy 배열을 나누기
  Numpy 배열을 나눌 때에는 split() 함수를 사용하며 이는 concatenate() 함수와 흡사하게 동작합니다. 2 X 4 배열을 왼쪽과 오른쪽으로 이등분하는 소스코드는 다음과 같습니다.



In [7]:
import numpy as np 
array = np.arange(8).reshape(2, 4) 
left, right = np.split(array, [2], axis=1) 
print(left.shape) 
print(right.shape) 
print(right[1][1])



(2, 2)
(2, 2)
7


# 파이썬(Python) Numpy의 연산과 함수
파이썬(Python)의 넘파이(Numpy) 라이브러리에서는 다양한 기본 연산을 지원합니다. 기본적인 사칙연산을 지원하는데, 이러한 연산들은 배열 안에 포함되어 있는 원소에 대한 연산입니다. 예를 들어 배열의 모든 원소의 값에 10을 더하는 등의 작업을 수행할 수 있습니다. 저는 1부터 9까지의 숫자를 랜덤하게 3개만큼 생성하여 각 원소에 10씩 더하도록 프로그래밍을 해보았습니다.

In [8]:
import numpy as np
array = np.random.randint(1, 10, size=3) 
result_array = array + 10 
print(result_array[0], result_array[1], result_array[2])



12 14 16


 당연히 곱셈 또한 가능합니다.

In [9]:
import numpy as np

array = np.random.randint(1, 10, size=3)
result_array = array * 10
print(result_array[0], result_array[1], result_array[2])




10 40 50


  또한 이러한 Numpy의 연산은 Numpy 배열의 형태와 관계 없이 사용할 수 있습니다

In [10]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)

result_array = array * 10

print(result_array[0][0], result_array[1][0], result_array[1][1])


50 80 60


# 서로 다른 형태의 Numpy 연산
  서로 다른 형태를 가진 Numpy 배열 끼리도 연산할 수 있습니다. 이 때는 기본적으로 행우선으로 연산이 이루어집니다.


In [11]:
import numpy as np 
array1 = np.arange(4).reshape(2, 2) 
array2 = np.arange(2) 
array3 = array1 + array2 
print(array3[0][0], array3[0][1], array3[1][0], array3[1][1])


0 2 2 4


서로 다른 형태(Shape이 다를 때)의 Numpy를 연산할 때에는 브로드캐스트(Broadcast)가 적용됩니다. 다시 말해 브로드캐스트란 서로 모양이 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환하는 기법입니다.



  예를 들어



1 2 3

4 5 6

7 8 9



와



1 2 3을 더하면,



2 4 6

5 7 9

8 10 12



가 됩니다.

In [12]:
array1 = np.arange(1, 10)
array1 = array1.reshape(3, 3)

array2 = np.arange(1, 4)

print(array1 + array2)

  # 브로드캐스트는 최소한 하나의 배열의 차원의 크기가 1일 때 가능합니다.

  # 브로드캐스트는 차원에 대해서 축의 길이가 같을 때 사용이 가능합니다.


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]



  그러므로 1 X 4인 배열과 4 X 1인 배열끼리도 덧셈이 가능한 것입니다. 이 때 자동으로 브로드캐스트가 적용되어 1 X 4는 4 X 4로 확장 되고, 4 X 1 또한 4 X 4로 확장 되어 연산이 이루어진다고 볼 수 있습니다.

In [13]:
import numpy as np

array1 = np.arange(4).reshape(4, 1)
array2 = np.arange(4)
array3 = array1 + array2

print(array3[0][0], array3[0][1], array3[0][2], array3[0][3])
print(array3[1][0], array3[1][1], array3[1][2], array3[1][3])
print(array3[2][0], array3[2][1], array3[2][2], array3[2][3])
print(array3[3][0], array3[3][1], array3[3][2], array3[3][3])


0 1 2 3
1 2 3 4
2 3 4 5
3 4 5 6


  또한 Numpy는 마스킹 연산도 수행이 가능합니다. 이는 각 원소가 특정한 조건을 만족하는지에 대한 결과가 배열 형태로 반환이 이루어집니다.

In [14]:
import numpy as np

# Numpy 원소의 값을 조건에 따라 바꿀 때는 다음과 같이 합니다.
# 반복문을 이용할 때보다 매우 빠르게 동작합니다.
# 대체로 이미지 처리(Image Processing)에서 자주 활용됩니다.
array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


# Numpy의 연산 함수
 Numpy는 다양한 기본 함수들을 제공합니다.

In [15]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))



최대값: 15
최소값: 0
합계: 120
평균값: 7.5


 가로 축에 대한 집계도 가능합니다.

In [16]:
import numpy as np 
array = np.arange(16).reshape(4, 4)
print("합계:", np.sum(array, axis=0))


합계: [24 28 32 36]
