#모두의 인공지능 기초 수학

모두의 인공지능 <br>
https://thebook.io/080246/

image.png

# Part 1 기초수학

## 1장 방정식과 부등식

### 1.1 변수와 수식

1.1.1 변수

In [27]:
# 변수와 상수


# x 변수에 값 5를 저장
x=5
print(x)

5


In [28]:
# x, y, z 변수에 값 1, 2, 3을 각각 저장
x, y, z = 1, 2, 3
print(x, y, z)

1 2 3


In [29]:
#파이썬에서의 수식

a, b, c = 3, 7, 2

#####더하기

In [30]:
a+b     #3+7

10

#####빼기

In [31]:
a-b     #3-7

-4

#####곱하기

In [32]:
a*b     #3*7

21

#####나누기

In [33]:
b/a     #7/3

2.3333333333333335

#####나머지

In [34]:
b%a     #7%2

1

#####제곱

In [35]:
a**c    #3의 제곱

9

#####몫

In [36]:
a//c    #3을 2로 나눈 몫

1

### 1.2 방정식과 부등식

#### 1.2.1 방정식

In [37]:
# 일차방정식과 이차방정식


# anaconda prompt창에서 
# pip install numpy 실행하여 numpy 라이브러리를 설치합니다
# pip install sympy 실행하여 sympy 라이브러리를 설치합니다

In [38]:
# sympy 라이브러리를 불러오고, 사용할 기호 변수를 선언한다.
from sympy import Symbol, solve
x=Symbol('x')

# 방정식을 풀기 위해서는 “(방정식) = 0”으로 만들어 줘야 한다. 이를 위해 모든 식을 좌변으로 이항시켜준 후, equation으로 변수화해준다
equation = 2 * x - 6

# 방정식을 풀기 위해 sympy에 내장된 solve() 함수를 사용한다. solve() 함수를 사용하기 위해 equation을 입력해주면 방정식을 풀어서 결과를 반환한다.
solve(equation)

[3]

In [39]:
# 일차방정식과 이차방정식의 python 연습 문제 풀이(1)

from sympy import Symbol, solve
k=Symbol('k')
equation = k-2-4
solve(equation)

[6]

In [40]:
# 일차방정식과 이차방정식의 python 연습문제 풀이(3)

from sympy import Symbol, solve
k=Symbol('k')
equation = k/2 - 8
solve(equation)

[16]

#####연립방정식

In [41]:
# 연립방정식
# sympy 라이브러리를 불러오고, 사용할 기호 변수 x, y를 선언한다.
from sympy import Symbol, solve
x=Symbol('x')
y=Symbol('y')

# 방정식을 풀기 위해서는 “(방정식) = 0”으로 만들기 위해 모든 식을 좌변으로 이항시켜준 후, equation1과 equation2로 변수화해준다
equation1 = 3 * x + y - 2
equation2 = x - 2 * y - 3

# 방정식을 풀기 위해 sympy에 내장된 solve() 함수를 사용한다. solve() 함수를 사용하기 위해 equation을 차례로 입력해주면 방정식을 풀어서 결과를 반환한다.
solve((equation1, equation2), dict=True)  # dict 옵션은 해를 사전 형태로 반환한다.

[{x: 1, y: -1}]

## 4장 지수와 제곱근

### 4.2 거듭제곱과 거듭제곱근

#### 4.2.2 거듭제곱근

In [42]:
# 거듭제곱의 표현은 **으로 한다.
2**5

32

In [43]:
# math.sqrt() 함수를 이용하여 제곱근을 구한다.
import math   # math는 추가 설치없이 사용 가능합니다.
math.sqrt(2)

1.4142135623730951

In [44]:
math.sqrt(9)

3.0

### 4.3 인수분해

#### 4.3.1 인수분해


In [45]:
# 파이썬 sympy의 extend, factor, symbol을 호출하고, 기호 변수 x를 선언한다.
from sympy import expand, factor
from sympy import Symbol
x = Symbol('x')

In [46]:
# extend()는 수식을 전개하는 함수로 (x + 1) x (x + 5)를 전개한다.
expand((x + 1) * (x + 5))

x**2 + 6*x + 5

In [47]:
# factor()는 인수분해하는 함수로, x2+6x+5를 인수분해한다.
factor(x**2 + 6*x + 5)

(x + 1)*(x + 5)

## 6장 지수함수와 로그함수

### 6.1 지수함수

#### 6.1.1 지수함수와 그래프

In [48]:




# 파이썬 math 라이브러리 호출
import math

In [49]:
# 파이썬에서 제공하는 지수함수 유형별로 실행
# 2의 5제곱
pow=math.pow(2, 5)
print("pow 결과:", pow)

# 2의 제곱근
sqrt=math.sqrt(2)
print("sqrt 결과:", sqrt)

# e의 2제곱
exp=math.exp(2)
print("exp 결과:", exp)

pow 결과: 32.0
sqrt 결과: 1.4142135623730951
exp 결과: 7.38905609893065


### 6.2 로그함수

#### 6.2.1 로그함수와 그래프

In [50]:
# 파이썬 math 라이브러리 호출
import math

# log 값을 얻기 위해 math 라이브러리의 log() 함수를 사용한다.
math.log(2,4)  # y1=log42

0.5

In [51]:
math.log(4,2)  # y1=log24

2.0

# Part 2 미분

## 7장 함수의 극한과 연속


### 7.1 함수의 극한과 연속


####7.1.2 함수의 극한

In [52]:
# Part 2 미분

# 함수의 발산

# 파이썬 sympy 라이브러리에서 Limit, S, Symbol 클래스를 호출한다.
from sympy import Limit, S, Symbol

# x 변수를 생성하고, x가 0으로 한없이 가까워질 때의 1/x에 대한 극한값을 구한다.
x=Symbol('x')
Limit(1/x, x, S.Infinity).doit()

0

In [53]:
Limit(1/x, x, 0).doit()             # 우극한 값 구하기

oo

In [54]:
Limit(1/x, x, 0, dir='-').doit()  # 좌극한 값 구하기 

-oo

## 8장 다항함수의 미분

### 8.1 다항함수의 미분

####8.1.1 평균변화율

In [55]:
from sympy import symbols    # 파이썬 Numpy 라이브러리 호출
def average(a,b):
    m = max(a,b)      #a, b의 최댓값
    n = min(a,b)      #a, b의 최솟값
    x = symbols('x')  #기호변수 x 선언

    fx = 2 * x ** 2 + 4 * x *  + x + 7 # 2x^2 + 4x + 7 함수 정의
    fb = fx.subs(x, m)  #함수에 m 대입
    fa = fx.subs(x, n)  #함수에 n 대입

    result = (fb - fa) / (m - n)
    return result
print(average(0,2))

12


#### 8.1.2 미분계수

In [56]:


# 파이썬 Numpy 라이브러리 호출
from sympy import Derivative, symbols

# 평균변화율을 구할 수 있는 함수 정의
x = symbols('x')   # x를 기호 변수화
fx = 2 * x ** 2 + 4 * x *  + x + 7

# fprime라는 Derivative 클래스의 객체를 생성한 후
# subs() 메서드를 이용하여 x=3에서의 미분계수 f′(3)을 구한다.
fprime = Derivative(fx, x).doit()  #x에 대해서 미분
n = fprime.subs({x: 3})
print("fx에서 x = 3 에서의 순간변화율(미분계수는) ", n , "입니다")

fx에서 x = 3 에서의 순간변화율(미분계수는)  36 입니다


#### 8.1.3 도함수

In [57]:

# 파이썬 SymPy 라이브러리 호출
from sympy import Derivative, symbols

# 변수 x와 함수 fx 정의
x = symbols('x')   # x를 기호 변수화
fx = 2 * x ** 2 + 4 * x *  + x + 7

Derivative(fx, x).doit()

12*x

In [58]:
# 연습문제
from sympy import Derivative, symbols
x = symbols('x') 
fx = 2 * x ** 2 -1 
Derivative(fx, x).doit()

4*x

#### 8.1.5 다항함수의 미분법

In [59]:


import sympy as sym
x = sym.Symbol('x')
a = sym.diff((2*x**3+3*x**2+x+1),x)
print(a)

6*x**2 + 6*x + 1


# Part 3 선형대수학

## 10장 벡터와 공간

### 10.1 벡터

#### 10.1.2 벡터란

##### 벡터란

In [60]:
# Part 3 선형대수학


# Numpy 라이브러리 호출
import numpy as np
x = np.array([1, 2, 3]) # 크기가 (3, )인 1차원 배열의 표현
print(x)

[1 2 3]


In [61]:
u = np.array([[1, 2, 3]])  # 크기가 (1, 3)인 2차원 배열의 표현(행 벡터)
print(u)

[[1 2 3]]


In [62]:
v = np.array([[1], [2], [3]]) # 크기가 (3, 1)인 2차원 배열의 표현(열 벡터)
print(v)

[[1]
 [2]
 [3]]


##### 벡터의 표현(확률분포를 벡터로 표현)

In [63]:

{1: 1/3, 2: 2/3, 3: 0/3}

{1: 0.3333333333333333, 2: 0.6666666666666666, 3: 0.0}

####10.1.3 특수한 벡터

##### 단위벡터


In [64]:

# 벡터란

import numpy as np
from scipy import linalg

# 단위 벡터를 위해 두가지 방법을 사용할 수 있다.
# NumPy의 서브 패키지인 linalg에서 제공하는 함수 norm()을 사용하여 
# 벡터의 크기를 계산한 후 기존 벡터로 나눠준다.

s=np.array([2,3,1])
v_hat01 = s / linalg.norm(s)
print(v_hat01)

[0.53452248 0.80178373 0.26726124]


In [65]:
# 파이썬 문제풀이(1)

import numpy as np
x=np.array([1, -3])
v_hat = x / linalg.norm(x)
print(v_hat)

[ 0.31622777 -0.9486833 ]


In [66]:
# 파이썬 문제풀이(2)

import numpy as np
x=np.array([-6,-8])
v_hat2 = x / (x**2).sum()**0.5
v_hat2

array([-0.6, -0.8])

In [67]:
# 파이썬 문제풀이(3)
import numpy as np
x=np.array([-5, -4])
v_hat = x / linalg.norm(x)
print (v_hat)

[-0.78086881 -0.62469505]


##### 영벡터


In [68]:


import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros(5).shape 

(5,)

In [70]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

### 10.2 선형 결합과 선형 독립

#### 10.2.1 선형 결합(linear combination)과 생성(span)

In [71]:



import numpy as np
a = np.array([2,4])
b = np.array([1,6])
c=(4*a)+((-3)*b)
print(c)

[ 5 -2]


#### 10.2.3 부분공간과 부분공간의 기저

##### 랭크(rank)

In [72]:

# 랭크(rank)

import numpy as np
X1 = np.array([[2, 7], [5, 1]])
np.linalg.matrix_rank(X1)

2

In [73]:
X1 = np.array([[2, 4], [3, 6]])
np.linalg.matrix_rank(X1)

1

In [74]:
# 파이썬 문제풀이(1)

import numpy as np
X1 = np.array([[1, 2], [3, 5]])
np.linalg.matrix_rank(X1)

2

In [75]:
# 파이썬 문제풀이(2)

import numpy as np
X1 = np.array([[1, 2], [3, 6]])
np.linalg.matrix_rank(X1)

1

### 10.3 벡터의 내적과 외적

#### 10.3.1 벡터의 덧셈과 뺄셈

#####벡터의 덧셈

In [76]:


# 벡터의 덧셈

x=[2,3]
y=[3,1]
z=[i+j for i, j in zip(x,y)]
print(z)

[5, 4]


In [77]:
# 노트

list(zip([1, 2, 3], [4, 5, 6]))

[(1, 4), (2, 5), (3, 6)]

In [78]:
list(zip([1, 2, 3], [4, 5, 6], [7, 8, 9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [79]:
# NumPy 라이브러리 이용한 간단한 코드

import numpy as np
u = np.array(x)
v = np.array(y)
w=u+v
print(w)

[5 4]


In [80]:
# 파이썬 문제풀이(1)

import numpy as np
x=[-4,5]
y=[-2,8]
u = np.array(x)
v = np.array(y)
w=u+v
print(w) 

[-6 13]


In [81]:
# 파이썬 문제풀이(2)

import numpy as np
x=[11,2]
y=[4,-3]
u = np.array(x)
v = np.array(y)
w=u+v
print(w) 

[15 -1]


In [82]:
# 파이썬 문제풀이(3)

import numpy as np
x=[-13,53]
y=[-25,-34]
u = np.array(x)
v = np.array(y)
w=u+v
print(w)  

[-38  19]


#####벡터의 뺄셈

In [83]:
# 벡터의 뺄셈

x=[2,3]
y=[3,1]
z=[i-j for i, j in zip(x,y)]
print(z)

[-1, 2]


In [84]:
# NumPy 라이브러리 이용한 간단한 코드

import numpy as np
u = np.array(x)
v = np.array(y)
w=u-v
print(w) 

[-1  2]


In [85]:
# 파이썬 문제풀이(1)

import numpy as np
x=[-7,15]
y=[-9,4]
u = np.array(x)
v = np.array(y)
w=u-v
print(w) 

[ 2 11]


In [86]:
# 파이썬 문제풀이(2)

import numpy as np
x=[-11,6]
y=[8,-14]
u = np.array(x)
v = np.array(y)
w=u-v
print(w)  

[-19  20]


In [87]:
# 파이썬 문제풀이(3)

import numpy as np
x=[-11,14]
y=[-19,-21]
u = np.array(x)
v = np.array(y)
w=u-v
print(w) 

[ 8 35]


#### 10.3.2 벡터의 곱셈

##### 벡터의 내적


In [88]:
# 10.3.2 벡터의 곱셈
# 벡터의 내적

x=[3,4]
c=8
z=[c*I for I in x]
print(z)

[24, 32]


In [89]:
# NumPy 라이브러리 이용한 간단한 코드

import numpy as np
u = np.array([3,4])
c = 8
w=u*c
print(w)

[24 32]


In [90]:
# 벡터의 내적(inner product)

import numpy as np
u = np.array([6,6])
v = np.array([12,0])
uv = np.dot(u, v)
print(uv)

72


In [91]:
# numpy.dot()를 이용하여 벡터의 내적

import numpy as np
A = np.arange(1*2*3).reshape((1,2,3))
B1 = np.arange(1*2*3).reshape((1,2,3))
B2 = np.arange(1*2*3).reshape((1,3,2))
B3 = np.arange(1*2*3).reshape((2,1,3))
B4 = np.arange(1*2*3).reshape((2,3,1))
B5 = np.arange(1*2*3).reshape((3,1,2))
B6 = np.arange(1*2*3).reshape((3,2,1))
np.dot(A,B1) # 결과는 오류가 맞습니다

ValueError: ignored

In [92]:
np.dot(A,B2)

array([[[[10, 13]],

        [[28, 40]]]])

In [ ]:
np.dot(A,B3) # 결과는 오류가 맞습니다

In [93]:
np.dot(A,B4)

array([[[[ 5],
         [14]],

        [[14],
         [50]]]])

In [ ]:
np.dot(A,B5) # 결과는 오류가 맞습니다

In [ ]:
np.dot(A,B6) # 결과는 오류가 맞습니다

In [94]:
# 파이썬 문제풀이(1)

import numpy as np
u = np.array([3, -6])
v = np.array([-7, 9])
uv = np.dot(u, v)
print(uv)    

-75


In [95]:
# 파이썬 문제풀이(2)

import numpy as np
u = np.array([-3, 4, 7])
v = np.array([-4, -9, 5])
uv = np.dot(u, v)
print(uv)    

11


In [96]:
# 파이썬 문제풀이(3)

import numpy as np
u = np.array([3, -11, 7])
v = np.array([-4, -13, 9])
uv = np.dot(u, v)
print(uv)

194


In [97]:
# 벡터의 외적
a = (1, 3, 5) 
b = (2, 4, 6)

# 벡터의 외적을 위한 수식을 함수로 구현
def cross(a, b):
    c = [a[1]*b[2] - a[2]*b[1],
    a[2]*b[0] - a[0]*b[2],
    a[0]*b[1] - a[1]*b[0]]
    return c
cross(a,b)

[-2, 4, -2]

In [98]:
# Numpy 이용한 벡터 외적 계산
import numpy as np      
print(np.cross(a,b))    # cross() 함수 이용한 결과

[-2  4 -2]


In [99]:
# 파이썬 문제풀이(1)
import numpy as np
a = np.array([5, -13, 8])
b = np.array([-2, 11, -14])
print(np.cross(a,b))

[94 54 29]


In [100]:
# 파이썬 문제풀이(2)
import numpy as np
a = np.array([-7, 8, -16])
b = np.array([-8, -5, 2])
print(np.cross(a,b))

[-64 142  99]


#### 10.3.3 직교벡터

##### 벡터의 크기


In [101]:
# 10.3.3 직교벡터
# 벡터의 크기와 거리
# 벡터의 크기

# 벡터  = (1, 2)일 때,  의 길이를 구해 보자.
import numpy as np
a = np.array([1,2])
print(a)

[1 2]


In [102]:
np.linalg.norm(a) # a의 길이

2.23606797749979

In [103]:
np.linalg.norm(a, ord=1) # L1 Norm 구하기

3.0

In [104]:
np.linalg.norm(a, ord=2) # L2 Norm 구하기

2.23606797749979

In [105]:
# 파이썬 문제풀이(1)

import numpy as np
a = np.array([-2,12])
np.linalg.norm(a)

12.165525060596439

In [106]:
# 파이썬 문제풀이(2)

import numpy as np
a=np.array([5**0.5,12])
np.linalg.norm(a)

12.206555615733702

In [107]:
# 파이썬 문제풀이(3)

import numpy as np
a=np.array([3,-15,8])
np.linalg.norm(a)

17.26267650163207

In [108]:
# 파이썬 문제풀이(4)

import numpy as np
a=np.array([-7,10**0.5,4])
np.linalg.norm(a)

8.660254037844387

##### 벡터의 거리/유사도

In [109]:
# 벡터의 거리/유사도
# Python을 활용한 벡터의 거리계산(유클리드 거리)

# scipy.spatia 모듈로부터 distance 함수 호출
from scipy.spatial import distance

# 두 점 P1과 P2 명시
p1 = (1, 2, 3)
p2 = (4, 5, 6)

# P1과 P2 사이의 유클리드 거리 계산
d = distance.euclidean(p1, p2)
print("Euclidean distance: ",d)

Euclidean distance:  5.196152422706632


##### 맨해튼 거리(Manhattan distance)

In [110]:
# 맨해튼 거리(Manhattan distance)

# math 함수 호출
from math import*

# 두 점 P1과 P2 정의
p1 = (1, 2, 3)
p2 = (4, 5, 6)

# 맨해튼 거리를 계산하기 위한 사용자 정의 함수 생성
def manhattan_distance(x,y):
    return sum(abs(a-b) for a,b in zip(x,y))

# P1과 P2 사이의 맨해튼 거리 계산
manhattan_distance(p1,p2)

9

##### 코사인 유사도(Cosine Similarity)

In [111]:
# 코사인 유사도(Cosine Similarity)

from numpy import dot
from numpy.linalg import norm
import numpy as np

def cos_sim(A, B):
    return dot(A, B)/(norm(A)*norm(B))

doc1=np.array([1,1,1,1,0])
doc2=np.array([1,0,1,0,1])
doc3=np.array([2,1,1,1,1])

print(cos_sim(doc1, doc2)) #문서1과 문서2의 코사인 유사도
print(cos_sim(doc1, doc3)) #문서1과 문서3의 코사인 유사도
print(cos_sim(doc2, doc3)) #문서2과 문서3의 코사인 유사도

0.5773502691896258
0.8838834764831843
0.8164965809277259


## 11장 행렬변환

### 11.2 역함수와 역변환

#### 11.2.2 역행렬

In [112]:
# 11장 행렬변환
# 11.2 역함수와 역변환
# 11.2.2 역행렬

import numpy as np
A = np.matrix([[1, 0, 0, 0], [2, 1, 0, 0], [3, 0, 1, 0], [4, 0, 0, 1]])
print(np.linalg.inv(A))

[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [-3.  0.  1.  0.]
 [-4. -0. -0.  1.]]


In [113]:
# 파이썬 문제풀이(1)

import numpy as np
A = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [114]:
# 파이썬 문제풀이(2)

import numpy as np
A = np.matrix([[2,3],[4,6]])
print(np.linalg.inv(A)) # 결과는 오류가 맞습니다

LinAlgError: ignored

### 11.3 전치행렬

#### 11.3.1 전치행렬이란

In [115]:
# 11.3 전치행렬
# 11.3.1 전치행렬이란

import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [116]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 12장 상호좌표계

### 12.1 고유값(eigenvalue), 고유벡터(eigenvector), 공유공간

#### 12.1.1 고유값과 고유벡터란

In [117]:
# 12장 상호좌표계
# 12.1 고유값(eigenvalue), 고유벡터(eigenvector), 공유공간
# 12.1.1 고유값과 고유벡터란

import numpy as np
a = np.array([[5,-1],[-2,1]])
w, v = np.linalg.eig(a)

print(w)
print(v)

[5.44948974 0.55051026]
[[ 0.91209559  0.21927526]
 [-0.40997761  0.97566304]]


In [118]:
# 파이썬 문제풀이
import numpy as np
a = np.array([[1,3],[4,2]])
w, v = np.linalg.eig(a)  
print(w)
print(v)

[-2.  5.]
[[-0.70710678 -0.6       ]
 [ 0.70710678 -0.8       ]]
